apiVersion: v1
kind: Pod
metadata:
  name: mysqldb
spec:
  containers:
  - image: kodekloud/simple-webapp-mysql
    env:
    - name: HEADER
      value: "SHAJAINI & SOWMYA"
    name: webapp-sqldb
    volumeMounts:
    - name: html
      mountPath: /var/htdocs
    ports:
    - containerPort: 80
      protocol: TCP
  volumes:
  - name: html
    emptyDir: {}
